apiVersion: v1
kind: ConfigMap
metadata:
  name: shoppingcart-config
data:
  application.properties: |
    spring.application.name=shopping-cart
    app.default-region=UK
    app.default-currency=GBP
    app.max-basket-items=100
    app.price.round-up=true
    logging.level.com.example.shoppingcart=INFO
    spring.cache.type=redis
    spring.cache.redis.time-to-live=3600000
---
apiVersion: v1
kind: Secret
metadata:
  name: shoppingcart-secrets
type: Opaque
stringData:
  jwt-secret: your-256-bit-secret-key-here
  aws-access-key: your-aws-access-key
  aws-secret-key: your-aws-secret-key
  redis-password: your-redis-password

